version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "90:90"
    volumes:
      - .:/var/www/laganstudio-admin

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
