version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "90:80"
    volumes:
      - .:/var/www/laganstudio-admin

  db:
    image: postgres:15
    container_name: laravel_db
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
    ports:
      - "5432:5432"
